# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  
  # Creates Hostname for machine
  config.vm.hostname = "ubuntu-eclipse-che"
  
  #  Configures networks on the machine.    
  config.vm.network "forwarded_port", host: 8080, guest: 8080
  for i in 32700..32800
    config.vm.network :forwarded_port, guest: i, host: i
  end
    
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search
  config.vm.box = "ubuntu/trusty64"    
  # config.vm.box = "ubuntu/trusty32"
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  config.vm.provider "virtualbox" do |vb|
     # Virtual Box Name
     vb.name = "ubuntu-eclipse-che" 
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
     # Vboxmanage customizations       
     vb.customize ["modifyvm", :id,
            "--natdnshostresolver1", "on"]  
  end
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.  
    config.vm.provision "shell", path: "../eclipse/che.sh"
end
